# This starter workflow is for a CMake project running on a single platform.
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Build
      working-directory: ${{ github.workspace }}
      # Build your program with the given configuration
      run: ./build.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ${{ github.workspace }}/build

  lexer-test:
    runs-on: macos-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: ${{ github.workspace }}/build

    - name: Lexer Test
      working-directory: ${{ github.workspace }}/build
      run: ./LexerTest

  parser-test:
    runs-on: macos-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: ${{ github.workspace }}/build

    - name: Parser Test
      working-directory: ${{ github.workspace }}/build
      run: ./ParserTest

  typechecker-test:
    runs-on: macos-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: ${{ github.workspace }}/build

    - name: TypeChecker Test
      working-directory: ${{ github.workspace }}/build
      run: ./TypeCheckerTest
